server:
  port: 8081

spring:
  profiles:
    include: db
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
    paths-to-match:
      - /**

jwt:
  secret: MDwwDQYJKoZIhvcNAQEBBQADKwAwKAIhAIqwfgdpBCIj/Kk4qtsIDrRjuABSI+rj69wlm+4eqU65AgMBAAE=
  token-validity-in-seconds: 86400

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password : miniArt10!

cloud:
  aws:
    credentials:
      accessKey: ENC(VQfeJ+6u0jtYVVXJbpehJMVkBPsWyQE6FSLErRc0u8E=)
      secretKey: ENC(RZPkWLadSjfpW8JAN4YoegBicuNlh34cTtb73SQPl0tignkmcS1FRQEBy/qXTQmobW0GGDTaE/E=)
    s3:
      bucket: mini-art-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false