spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/til-back
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      hbm2ddl.auto: update
#          ddl-auto: create
    properties:
      hibernate:
        #         show_sql: true
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ENC(LMbLcampRt9GtQ1h/CpD5rtocQYopjHkBZQBBKrleu0tMKeyYHgxNsTWTJj55BnHIKMSZOjyxjyvyMqJRgRiDyCLX12wvtuPiVLj7wikei5qWUX7CrxLwsbcsphyfHxg)
    username: ENC(gcNZpdpwOAapp1Mn5z/dKw==)
    password: ENC(DFBE0sJ3qjUvKi4bHbcJAUQ6DRNvxVVY)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            redirect-uri: http://localhost:8081/login/oauth2/code/google
            scope:
              - profile
              - email
          kakao:
            client-id: ${kakao-client-id}
            client-secret: ${kakao-client-secret}
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
            client-authentication-method: POST
            scope:
              - profile_nickname
              - account_email
          naver:
            client-id: ${naver-client-id}
            client-secret: ${naver-client-secret}
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
#            client-authentication-method: POST
            scope:
              - nickname
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail-id}
    password: ${gmail-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 600000
logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.type: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

upload:
  path: /Users/hmmini/mini/develop/project/backend/asset/

ses:
  mail: no-reply@mini-art-blog.com

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ENC(LMbLcampRt9GtQ1h/CpD5rtocQYopjHkBZQBBKrleu0tMKeyYHgxNsTWTJj55BnHIKMSZOjyxjyvyMqJRgRiDyCLX12wvtuPiVLj7wikei5qWUX7CrxLwsbcsphyfHxg)
    username: ENC(gcNZpdpwOAapp1Mn5z/dKw==)
    password: ENC(DFBE0sJ3qjUvKi4bHbcJAUQ6DRNvxVVY)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
#        format_sql: false
  data:
    redis:
      host: ${elasticache-endpoint}
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            redirect-uri: http://mini-art-blog.com:8081/login/oauth2/code/google
            scope:
              - profile
              - email
          kakao:
            client-id: ${kakao-client-id}
            client-secret: ${kakao-client-secret}
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
            client-authentication-method: POST
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail-id}
    password: ${gmail-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 600000
logging:
  level:
    org.hibernate.SQL: info
    # org.hibernate.type: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error


decorator:
  datasource:
    p6spy:
      enable-logging: false

upload:
  path: /asset/

ses:
  mail: no-reply@mini-art-blog.com