server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/til-back
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
#      hbm2ddl.auto: create
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
    paths-to-match:
      - /**

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

jwt:
  secret: MDwwDQYJKoZIhvcNAQEBBQADKwAwKAIhAIqwfgdpBCIj/Kk4qtsIDrRjuABSI+rj69wlm+4eqU65AgMBAAE=
  token-validity-in-seconds: 86400