server:
  port: 8081

spring:
  profiles:
    include: db
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 148186008203-ft5v315bnmmkpul14tunhostecpbcv6s.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8081/login/oauth2/code/google
            scope:
              - email
              - profile

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
    paths-to-match:
      - /**

jwt:
  secret: ${jwt-secret}
  accessExpirationTime: 1800000   # 1800000 -> 30min // 10000 -> 10sec
  refreshExpirationTime: 604800000  # 604800000 -> 7days // 30000 -> 30sec

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password : ${jasypt-password}

cloud:
  aws:
    credentials:
      accessKey: ${aws-access-key}
      secretKey: ${aws-secret-key}
    s3:
      bucket: mini-art-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false